---
weight: 30
title: Asciidoc -- Welcome developers
layout: bundle
---

Welcome to the \{\{< product-c8y-iot >}} developer documentation!

Learn how to develop and deploy applications on top of our IoT platform
and integrate IoT data sources.

For our developer community, we offer a variety of sources to quickly
get started or to dig deeper into the matter.

If you are new to \{\{< product-c8y-iot >}}, you might want to learn
about the architecture, technical concepts and domain models behind
\{\{< product-c8y-iot >}}. The __Concepts guide__ serves as a starting
point for anyone technically interested in our IoT platform.

== Developer guides

Check out the following developer guides if you are looking for
step-by-step instructions to specific topics:

[width="100%",cols="<20%,<80%",options="header",]
|===
|Guide |Content
|link:/web/[Web SDK guide] |How to use the Web SDK to extend
applications with your own plugins, add your own applications or
implement further functionalities tailored to your use case.

|link:/microservice-sdk/introduction/[Microservice SDK guide] |How to
use the Microservice SDK to develop and deploy microservices
(server-side applications) to extend the \{\{< product-c8y-iot >}}
platform with customer-specific functionality. If you want to jump right
in, check out the Hello world tutorials for Java and C#.

|link:/device-sdk/introduction/[Device SDK guide] |How to integrate IoT
data sources with the \{\{< product-c8y-iot >}} platform. The *Device
SDK guide* provides detailed information on device integration using
MQTT, REST and C++.
|===

Moreover, the Streaming Analytics guide provides basics for
understanding how to create your own analytics or other business logic
in \{\{< product-c8y-iot >}} with Apama EPL.

== OpenAPI Specification

A complete OpenAPI Specification for the \{\{< product-c8y-iot >}} REST
API is available at
https://%7B%7B%3C%20domain-c8y%20%3E%7D%7D/api[https://\{\{< domain-c8y
>}}/api]. The OpenAPI Specification describes the entire \{\{<
product-c8y-iot >}} REST API (i.e. available endpoints, operations on
each endpoint, input and output for each operation, authentication
methods and more) following the OpenAPI 3.0 standard.

== Developer community

Collaborate with \{\{< product-c8y-iot >}} community experts on our
link:%7B%7B%3C%20link-sag-dev-community%20%3E%7D%7D[\{\{< company-sag
>}} \{\{< sag-dev-community >}}] website.

Here you can:

* Browse through our vast knowledge base of tutorials, articles, code
samples, tips and tricks.
* As questions, brainstorm solutions or discuss best practices in our
discussion forum
* Get the latest \{\{< company-sag >}} news and announcements

Moreover you will find links to further resources like
https://github.com/softwareag[GitHub].
