---
weight: 20
title: ASciidoc -- Get started using the UI
layout: bundle
---

Welcome to the \{\{< product-c8y-iot >}} user documentation!

Read about the concepts behind \{\{< product-c8y-iot >}} and get
detailed advice on using our standard applications (Cockpit, Device
Management and Administration) as well as various optional services.

If you are new to \{\{< product-c8y-iot >}}, you might want to learn
about the architecture, technical concepts and domain models behind
\{\{< product-c8y-iot >}}. The __Concepts guide__ serves as a starting
point for anyone technically interested in our IoT platform.

== User guides

Check out the following user guides which might serve as a starting
point:

[width="100%",cols="<25%,<75%",options="header",]
|===
|Guide |Content
|link:/users-guide/getting-started/[User guide] |The _User guide_ is the
main reference for working with our platform via the UI and provides
in-depth explanation on all aspects of the \{\{< product-c8y-iot >}}
default applications (Administration, Cockpit and Device Management).

|link:/device-tutorials/tutorials-introduction/[Device integration
tutorials] |Check out our *Device integration tutorials* if you are
looking for step-by-step instructions on integrating various demo
devices, for example for proof-of-concept purposes in your \{\{<
product-c8y-iot >}} environment.

|link:/edge/overview/[\{\{< product-c8y-iot >}} Edge] |Learn how to
install, run and operate \{\{< product-c8y-iot >}} Edge, the local
version of \{\{< product-c8y-iot >}}.
|===

If you are looking for more detailed information on device integration
using supported device protocols like LWM2M or OPC UA, refer to the
Protocol integration guide.

== eLearning

Visit the link:%7B%7B%3C%20link-sag-training%20%3E%7D%7D[\{\{<
company-sag >}} \{\{< learning-portal >}}] where you can find helpful
eLearning material to get started:

link:%7B%7B%3C%20link-sag-training-basic%20%3E%7D%7D[_\{\{<
product-c8y-iot >}} Basic_] is a self-paced training which provides a
jump-start into the \{\{< product-c8y-iot >}} platform offering in the
\{\{< company-sag >}} clouds. Short videos followed by hands-on labs on
your free trial \{\{< product-c8y-iot >}} tenant provide fundamental
knowledge on how you can connect and manage your remote assets, use
powerful analytics to derive insights and incorporate them into your
business processes using the \{\{< product-c8y-iot >}} platform.

== Additional resources

For more information and resources, see also
link:/welcome/additional-resources/[Additional resources].
